# Introduction {#training-intro}

Fieldwork training is arguably one of the most important activities of any survey and has one of the most substantial impacts on data quality. It serves several purposes: 

1. __Build fieldworker capability__. In-depth content training, extensive practicing and capability-based selection ensure that fieldworkers are capable of implementing the survey as designed. This is key to limiting measurement error and nonresponse error, as well as coverage error and sampling error if the survey includes listing and in-field sampling.  

1. __Standardize fieldworker behavior__. Repeated practicing under supervision and continuous feedback streamline how fieldworkers implement the survey. Reducing idiosyncratic behavior is important to mitigate the very damaging fieldworker effects.

1. __Scrutinize methodology__. Ideally, this is done during pre-testing and piloting. However, particularly when this has been insufficient, fieldwork training often is effectively the most detailed review of the questionnaires, translations, CAPI, and survey processes. Identifying and correcting mistakes is key to reducing specification error.


Unfortunately, in many surveys fieldwork training is not implemented effectively to produce fieldworkers that are fully capable of implementing the survey, or is inefficient by being too demanding on trainers, survey budget and timeline.

This guide gives recommendations on how to implement fieldwork training that effectively prepares field workers while not overburdening trainers or overstretching survey resources. 